steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE_NAME'
  - '--image'
  - '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:latest'
  - '--region'
  - '$_LOCATION'
  - '--port'
  - '7860'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'PROJECT_ID=$PROJECT_ID,LOCATION=$_LOCATION'
images:
- '$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:latest'
substitutions:
  _LOCATION: us-central1
  _REPOSITORY: ai-crash-lab
  _IMAGE: math-tutor
  _SERVICE_NAME: math-tutor-service

